import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDppTables1758848314578 implements MigrationInterface {
    name = 'AddDppTables1758848314578'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "factories" DROP CONSTRAINT "factories_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "photos_defect_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "defects" DROP CONSTRAINT "defects_inspection_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "defects" DROP CONSTRAINT "defects_defect_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inspections" DROP CONSTRAINT "inspections_lot_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inspections" DROP CONSTRAINT "inspections_inspector_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "approvals_lot_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "approvals_approved_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "activities_lot_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_lot_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "lots" DROP CONSTRAINT "lots_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "lots" DROP CONSTRAINT "lots_factory_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "events_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "events_lot_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lot_factories_lot_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lot_factories_factory_id"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_lot_factories_lot_factory"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_lot_factory_roles_fact_role"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_factory_roles_factory_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_defects_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activities_lot_ts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reports_client_month"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lots_client_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lots_factory"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_user"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "uq_user_role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "uq_users_client_email"`);
        // Create enum types only if they don't exist
        await queryRunner.query(`DO $$ BEGIN
            CREATE TYPE "public"."dpp_events_type_enum" AS ENUM('CREATED', 'PUBLISHED', 'PRODUCTION', 'INSPECTION', 'PACKING', 'SHIPMENT', 'REPAIR', 'RECYCLE', 'OTHER');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;`);

        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "dpp_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dpp_id" uuid NOT NULL, "type" "public"."dpp_events_type_enum" NOT NULL, "actor" character varying NOT NULL, "location" character varying, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "data" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f4e73999b3d78a6aa233d81be9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_event_ts" ON "dpp_events" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_event_type" ON "dpp_events" ("type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_event_dpp" ON "dpp_events" ("dpp_id") `);

        await queryRunner.query(`DO $$ BEGIN
            CREATE TYPE "public"."dpp_access_logs_view_enum" AS ENUM('PUBLIC', 'RESTRICTED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;`);

        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "dpp_access_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dpp_id" uuid NOT NULL, "view" "public"."dpp_access_logs_view_enum" NOT NULL, "ip" character varying(45) NOT NULL, "user_agent" character varying(1000), "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" character varying, "endpoint" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1e667f98d93c173cdddec60dbe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_access_ip" ON "dpp_access_logs" ("ip") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_access_ts" ON "dpp_access_logs" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_access_view" ON "dpp_access_logs" ("view") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_access_dpp" ON "dpp_access_logs" ("dpp_id") `);

        await queryRunner.query(`DO $$ BEGIN
            CREATE TYPE "public"."dpps_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;`);

        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "dpps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid NOT NULL, "schema_version" character varying NOT NULL DEFAULT 'textile.v0.1', "product_sku" character varying NOT NULL, "gtin" character varying, "brand" character varying NOT NULL, "style_ref" character varying NOT NULL, "public_payload" jsonb NOT NULL, "restricted_payload" jsonb NOT NULL DEFAULT '{}', "status" "public"."dpps_status_enum" NOT NULL DEFAULT 'DRAFT', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dc58128c648cbe6d19336537157" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_client" ON "dpps" ("client_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_status" ON "dpps" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_gtin" ON "dpps" ("gtin") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_dpp_sku" ON "dpps" ("product_sku") `);
        await queryRunner.query(`ALTER TABLE "lot_factories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "lot_factories" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lot_factories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "lot_factories" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP CONSTRAINT "UQ_2f2cc765582446a9fab4ac22e05"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "key" character varying`);
        await queryRunner.query(`UPDATE "supply_chain_roles" SET "key" = 'UNKNOWN_' || id WHERE "key" IS NULL`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ALTER COLUMN "key" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD CONSTRAINT "UQ_2f2cc765582446a9fab4ac22e05" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "name" character varying`);
        await queryRunner.query(`UPDATE "supply_chain_roles" SET "name" = 'Unknown Role ' || id WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "factory_roles" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "factory_roles" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "factory_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "factory_roles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "factory_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "factory_roles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "name" character varying(255)`);
        await queryRunner.query(`UPDATE "factories" SET "name" = 'Factory ' || id WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "factories" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "city" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "country" character varying(2) NOT NULL DEFAULT 'PT'`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP CONSTRAINT "defect_types_name_key"`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD "name" character varying`);
        await queryRunner.query(`UPDATE "defect_types" SET "name" = 'DefectType_' || id WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "defect_types" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD CONSTRAINT "UQ_e7312ad90c98550ad6614f9e8da" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD "category" character varying`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "photos" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "photos" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "photos" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "photos" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defects" DROP COLUMN "piece_code"`);
        await queryRunner.query(`ALTER TABLE "defects" ADD "piece_code" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "defects" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "defects" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defects" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "defects" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inspections" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inspections" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inspections" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inspections" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP COLUMN "decision"`);
        await queryRunner.query(`DO $$ BEGIN
            CREATE TYPE "public"."approvals_decision_enum" AS ENUM('APPROVE', 'REJECT');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD "decision" "public"."approvals_decision_enum"`);
        await queryRunner.query(`UPDATE "approvals" SET "decision" = 'APPROVE' WHERE "decision" IS NULL`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "decision" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "decided_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "ts"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "ts" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "type"`);
        await queryRunner.query(`DO $$ BEGIN
            CREATE TYPE "public"."reports_type_enum" AS ENUM('MONTHLY_SCORECARD', 'LOT');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "type" "public"."reports_type_enum"`);
        await queryRunner.query(`UPDATE "reports" SET "type" = 'LOT' WHERE "type" IS NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "status"`);
        await queryRunner.query(`DO $$ BEGIN
            CREATE TYPE "public"."reports_status_enum" AS ENUM('PENDING', 'READY', 'FAILED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "status" "public"."reports_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lots" DROP COLUMN "style_ref"`);
        await queryRunner.query(`ALTER TABLE "lots" ADD "style_ref" character varying(120)`);
        await queryRunner.query(`UPDATE "lots" SET "style_ref" = 'LOT_' || id WHERE "style_ref" IS NULL`);
        await queryRunner.query(`ALTER TABLE "lots" ALTER COLUMN "style_ref" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lots" DROP COLUMN "status"`);
        await queryRunner.query(`DO $$ BEGIN
            CREATE TYPE "public"."lots_status_enum" AS ENUM('PLANNED', 'IN_PRODUCTION', 'INSPECTION', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SHIPPED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;`);
        await queryRunner.query(`ALTER TABLE "lots" ADD "status" "public"."lots_status_enum" DEFAULT 'PLANNED'`);
        await queryRunner.query(`UPDATE "lots" SET "status" = 'PLANNED' WHERE "status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "lots" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lots" ALTER COLUMN "defect_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lots" ALTER COLUMN "inspected_progress" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lots" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "lots" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lots" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "lots" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "type"`);
        await queryRunner.query(`DO $$ BEGIN
            CREATE TYPE "public"."events_type_enum" AS ENUM('DEFECT_DETECTED', 'LOT_AWAITING_APPROVAL', 'LOT_DECIDED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;`);
        await queryRunner.query(`ALTER TABLE "events" ADD "type" "public"."events_type_enum"`);
        await queryRunner.query(`UPDATE "events" SET "type" = 'LOT_DECIDED' WHERE "type" IS NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "payload" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "payload" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "name" character varying(255)`);
        await queryRunner.query(`UPDATE "clients" SET "name" = 'Client_' || id WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "clients_slug_key"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "slug" character varying(120)`);
        await queryRunner.query(`UPDATE "clients" SET "slug" = 'client_' || id WHERE "slug" IS NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "UQ_2a850b0972b11500683fe49b3c4" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "logo_url" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "roles_name_key"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" character varying`);
        await queryRunner.query(`UPDATE "roles" SET "name" = 'Role_' || id WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "is_primary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255)`);
        await queryRunner.query(`UPDATE "users" SET "email" = 'user_' || id || '@example.com' WHERE "email" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255)`);
        await queryRunner.query(`UPDATE "users" SET "password_hash" = 'temp_hash_' || id WHERE "password_hash" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "client_id" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "entity"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "entity" character varying`);
        await queryRunner.query(`UPDATE "audit_log" SET "entity" = 'unknown_entity' WHERE "entity" IS NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ALTER COLUMN "entity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "entity_id" character varying`);
        await queryRunner.query(`UPDATE "audit_log" SET "entity_id" = 'unknown_' || id WHERE "entity_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ALTER COLUMN "entity_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "action" character varying`);
        await queryRunner.query(`UPDATE "audit_log" SET "action" = 'unknown_action' WHERE "action" IS NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ALTER COLUMN "action" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "ts"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "ts" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lot_factories" ADD CONSTRAINT "UQ_4b42cf590074197a1b727acd0a3" UNIQUE ("lot_id", "factory_id")`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" ADD CONSTRAINT "UQ_978d451ccde771ce889a944832a" UNIQUE ("lot_factory_id", "role_id")`);
        await queryRunner.query(`ALTER TABLE "factory_roles" ADD CONSTRAINT "UQ_5f509b21da69e3a377ceb6e3dca" UNIQUE ("factory_id", "role_id")`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "UQ_23ed6f04fe43066df08379fd034" UNIQUE ("user_id", "role_id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_c939118cb5d8f30edc66a626a7b" UNIQUE ("client_id", "email")`);
        await queryRunner.query(`ALTER TABLE "factories" ADD CONSTRAINT "FK_39fa445253769a08081a8b9485c" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_992e74d0c936c34f5e43b844259" FOREIGN KEY ("defect_id") REFERENCES "defects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "defects" ADD CONSTRAINT "FK_4ce8bd137e020c3c843df2f1e2a" FOREIGN KEY ("inspection_id") REFERENCES "inspections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "defects" ADD CONSTRAINT "FK_3dea2797377515adfee132358ba" FOREIGN KEY ("defect_type_id") REFERENCES "defect_types"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspections" ADD CONSTRAINT "FK_ae09f142a5cfb32324d3ef084d7" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspections" ADD CONSTRAINT "FK_be0708872a150482d84fafdf5ca" FOREIGN KEY ("inspector_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "FK_fbeefb6072cbf5161fec58b1c36" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "FK_6424e5974a58f747eaae00e7163" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_b79dacbbdd92259182f873944ed" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_bda44e16992191ff11ad8da01e2" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_875b7b8cbdbc9155c34561135bf" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lots" ADD CONSTRAINT "FK_52222ad1e6660451b31ea7e5780" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lots" ADD CONSTRAINT "FK_8e738387523ad9133f3f5ee2617" FOREIGN KEY ("factory_id") REFERENCES "factories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_b4ea5a78d656e3c29835bf644e6" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_8cebe14c096d6b4340d9046fe91" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0d1e90d75674c54f8660c4ed446" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dpp_events" ADD CONSTRAINT "FK_05fbad8a3a5dafac29d6dea64b7" FOREIGN KEY ("dpp_id") REFERENCES "dpps"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dpp_access_logs" ADD CONSTRAINT "FK_5eb01403cdb0e3b814011ea5ee5" FOREIGN KEY ("dpp_id") REFERENCES "dpps"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dpps" ADD CONSTRAINT "FK_8b619ab36496e04c1d67bfbc643" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dpps" ADD CONSTRAINT "FK_84cfbc26f63b938fadc8375b023" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dpps" DROP CONSTRAINT "FK_84cfbc26f63b938fadc8375b023"`);
        await queryRunner.query(`ALTER TABLE "dpps" DROP CONSTRAINT "FK_8b619ab36496e04c1d67bfbc643"`);
        await queryRunner.query(`ALTER TABLE "dpp_access_logs" DROP CONSTRAINT "FK_5eb01403cdb0e3b814011ea5ee5"`);
        await queryRunner.query(`ALTER TABLE "dpp_events" DROP CONSTRAINT "FK_05fbad8a3a5dafac29d6dea64b7"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0d1e90d75674c54f8660c4ed446"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_8cebe14c096d6b4340d9046fe91"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_b4ea5a78d656e3c29835bf644e6"`);
        await queryRunner.query(`ALTER TABLE "lots" DROP CONSTRAINT "FK_8e738387523ad9133f3f5ee2617"`);
        await queryRunner.query(`ALTER TABLE "lots" DROP CONSTRAINT "FK_52222ad1e6660451b31ea7e5780"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_875b7b8cbdbc9155c34561135bf"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_bda44e16992191ff11ad8da01e2"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_b79dacbbdd92259182f873944ed"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "FK_6424e5974a58f747eaae00e7163"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "FK_fbeefb6072cbf5161fec58b1c36"`);
        await queryRunner.query(`ALTER TABLE "inspections" DROP CONSTRAINT "FK_be0708872a150482d84fafdf5ca"`);
        await queryRunner.query(`ALTER TABLE "inspections" DROP CONSTRAINT "FK_ae09f142a5cfb32324d3ef084d7"`);
        await queryRunner.query(`ALTER TABLE "defects" DROP CONSTRAINT "FK_3dea2797377515adfee132358ba"`);
        await queryRunner.query(`ALTER TABLE "defects" DROP CONSTRAINT "FK_4ce8bd137e020c3c843df2f1e2a"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_992e74d0c936c34f5e43b844259"`);
        await queryRunner.query(`ALTER TABLE "factories" DROP CONSTRAINT "FK_39fa445253769a08081a8b9485c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_c939118cb5d8f30edc66a626a7b"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "UQ_23ed6f04fe43066df08379fd034"`);
        await queryRunner.query(`ALTER TABLE "factory_roles" DROP CONSTRAINT "UQ_5f509b21da69e3a377ceb6e3dca"`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" DROP CONSTRAINT "UQ_978d451ccde771ce889a944832a"`);
        await queryRunner.query(`ALTER TABLE "lot_factories" DROP CONSTRAINT "UQ_4b42cf590074197a1b727acd0a3"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "ts"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "ts" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "action" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "entity_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "entity"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "entity" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "client_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "is_primary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "roles_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "logo_url" text`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "UQ_2a850b0972b11500683fe49b3c4"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "slug" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "clients_slug_key" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "payload" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "payload" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."events_type_enum"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "type" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lots" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "lots" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lots" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "lots" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lots" ALTER COLUMN "inspected_progress" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lots" ALTER COLUMN "defect_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lots" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."lots_status_enum"`);
        await queryRunner.query(`ALTER TABLE "lots" ADD "status" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lots" DROP COLUMN "style_ref"`);
        await queryRunner.query(`ALTER TABLE "lots" ADD "style_ref" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "status" text DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "type" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "ts"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "ts" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "decided_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP COLUMN "decision"`);
        await queryRunner.query(`DROP TYPE "public"."approvals_decision_enum"`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD "decision" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inspections" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inspections" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inspections" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inspections" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defects" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "defects" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defects" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "defects" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defects" DROP COLUMN "piece_code"`);
        await queryRunner.query(`ALTER TABLE "defects" ADD "piece_code" text`);
        await queryRunner.query(`ALTER TABLE "photos" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "photos" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "photos" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "photos" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD "category" text`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP CONSTRAINT "UQ_e7312ad90c98550ad6614f9e8da"`);
        await queryRunner.query(`ALTER TABLE "defect_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "defect_types" ADD CONSTRAINT "defect_types_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "country" text DEFAULT 'PT'`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "city" text`);
        await queryRunner.query(`ALTER TABLE "factories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "factories" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "factory_roles" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "factory_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "factory_roles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "factory_roles" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "factory_roles" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP CONSTRAINT "UQ_2f2cc765582446a9fab4ac22e05"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD "key" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supply_chain_roles" ADD CONSTRAINT "UQ_2f2cc765582446a9fab4ac22e05" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "lot_factory_roles" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "lot_factories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "lot_factories" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lot_factories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "lot_factories" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_sku"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_gtin"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_client"`);
        await queryRunner.query(`DROP TABLE "dpps"`);
        await queryRunner.query(`DROP TYPE "public"."dpps_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_access_dpp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_access_view"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_access_ts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_access_ip"`);
        await queryRunner.query(`DROP TABLE "dpp_access_logs"`);
        await queryRunner.query(`DROP TYPE "public"."dpp_access_logs_view_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_event_dpp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dpp_event_ts"`);
        await queryRunner.query(`DROP TABLE "dpp_events"`);
        await queryRunner.query(`DROP TYPE "public"."dpp_events_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "uq_users_client_email" UNIQUE ("client_id", "email")`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "uq_user_role" UNIQUE ("user_id", "role_id")`);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_user" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_lots_factory" ON "lots" ("factory_id") `);
        await queryRunner.query(`CREATE INDEX "idx_lots_client_status" ON "lots" ("client_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_reports_client_month" ON "reports" ("client_id", "month") `);
        await queryRunner.query(`CREATE INDEX "idx_activities_lot_ts" ON "activities" ("lot_id", "ts") `);
        await queryRunner.query(`CREATE INDEX "idx_defects_type" ON "defects" ("defect_type_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_factory_roles_factory_role" ON "factory_roles" ("factory_id", "role_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_lot_factory_roles_fact_role" ON "lot_factory_roles" ("lot_factory_id", "role_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_lot_factories_lot_factory" ON "lot_factories" ("lot_id", "factory_id") `);
        await queryRunner.query(`CREATE INDEX "idx_lot_factories_factory_id" ON "lot_factories" ("factory_id") `);
        await queryRunner.query(`CREATE INDEX "idx_lot_factories_lot_id" ON "lot_factories" ("lot_id") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "events_lot_id_fkey" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "events_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lots" ADD CONSTRAINT "lots_factory_id_fkey" FOREIGN KEY ("factory_id") REFERENCES "factories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lots" ADD CONSTRAINT "lots_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_lot_id_fkey" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "activities_lot_id_fkey" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "approvals_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "approvals_lot_id_fkey" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspections" ADD CONSTRAINT "inspections_inspector_id_fkey" FOREIGN KEY ("inspector_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspections" ADD CONSTRAINT "inspections_lot_id_fkey" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "defects" ADD CONSTRAINT "defects_defect_type_id_fkey" FOREIGN KEY ("defect_type_id") REFERENCES "defect_types"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "defects" ADD CONSTRAINT "defects_inspection_id_fkey" FOREIGN KEY ("inspection_id") REFERENCES "inspections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "photos_defect_id_fkey" FOREIGN KEY ("defect_id") REFERENCES "defects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factories" ADD CONSTRAINT "factories_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
